apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-web-app
spec:
  selector:
    matchLabels:
      run: k8s-demo-web-app
  replicas: 1
  template: 
    metadata: 
      labels:
        run: k8s-demo-web-app
    spec: 
      containers:
        - name: k8s-demo-web-app
          image: localhost:5001/k8s-demo-web-app:latest
          ports:
            - containerPort: 3000
              hostPort: 9101
              protocol: TCP
