---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-web-service
spec:
  selector:
    run: k8s-demo-web-app
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      nodePort: 30010
      port: 3000
